"""
Django settings for library_automation project.

Generated by 'django-admin startproject' using Django 4.2.23.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY", "django-insecure-development-key-please-change-in-production")

# SECURITY WARNING: don't run with debug turned on in production!
# For local LAN testing and to capture tracebacks during setup, force DEBUG=True
# (temporary; revert this in production).
DEBUG = True

ALLOWED_HOSTS = [
    'localhost', 
    '127.0.0.1', 
    '.render.com',
    '.onrender.com',
    'iubat-smartlibrary.onrender.com',
    'iubat-smartlibrary-backend.onrender.com',  # Your actual backend domain
    # Add your specific Render domain here when you get it
]

# Try to auto-detect a LAN IP and add it to ALLOWED_HOSTS to simplify local network
# testing (useful for development/testing on a LAN). This won't override explicit
# ALLOWED_HOSTS if you set them via environment in production.
try:
    import socket
    s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    # doesn't need to be reachable; used only to determine the default outbound IP
    s.connect(("8.8.8.8", 80))
    local_ip = s.getsockname()[0]
    s.close()
    if local_ip and local_ip not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(local_ip)
except Exception:
    # If auto-detection fails, do nothing. You can still set ALLOWED_HOSTS manually.
    pass


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'corsheaders',
    'library.apps.LibraryConfig',
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    'corsheaders.middleware.CorsMiddleware',
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "library_automation.urls"

# ... other settings

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # Add a project-level templates directory for MVT-based frontend
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

# ... rest of your settings

WSGI_APPLICATION = "library_automation.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# Priority: DATABASE_URL (Neon) > local SQLite
DATABASE_URL = os.environ.get('DATABASE_URL', None)

if DATABASE_URL:
    # Production: Use Neon PostgreSQL
    DATABASES = {
        'default': dj_database_url.config(
            default=DATABASE_URL, 
            conn_max_age=600, 
            conn_health_checks=True,
            ssl_require=True
        )
    }
else:
    # Development: Use SQLite
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images) - Includes React build
# https://docs.djangoproject.com/en/4.2/howto/static-files/

# Serve static files under the /library path so the React build (which uses
# PUBLIC_URL=/library) can reference assets like /library/static/js/...
STATIC_URL = '/library/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Additional directories to search for static files used by server-rendered
# templates and admin UI. Keep this minimal now that the React frontend is
# removed from this branch.
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),  # backend static assets (css, images, etc.)
]

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# CORS settings for React frontend
CORS_ALLOWED_ORIGINS = [
    # Keep only production/back-end origins here. For local development the
    # `CORS_ALLOW_ALL_ORIGINS = DEBUG` setting allows access.
    "https://iubat-smartlibrary-backend.onrender.com",
]

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_ALL_ORIGINS = DEBUG  # Allow all in development only

# Additional CORS settings for browser compatibility
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'cookie',
    'set-cookie',
]

# Expose cookies in CORS responses
CORS_EXPOSE_HEADERS = [
    'set-cookie',
]

# Session settings for cross-origin cookies
SESSION_COOKIE_SAMESITE = 'None'  # Required for cross-site cookies
SESSION_COOKIE_SECURE = not DEBUG  # True in production (HTTPS), False in development
SESSION_COOKIE_HTTPONLY = False   # Allow JavaScript access to session cookies
SESSION_COOKIE_DOMAIN = '.onrender.com' if not DEBUG else None  # Share cookies across Render subdomains
SESSION_SAVE_EVERY_REQUEST = True # Ensure session is saved on every request

# CSRF settings for cross-origin requests
CSRF_COOKIE_SAMESITE = 'None'     # Required for cross-site cookies
CSRF_COOKIE_SECURE = not DEBUG    # True in production (HTTPS), False in development
CSRF_COOKIE_HTTPONLY = False      # Allow JavaScript access to CSRF cookies
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:3001",
    "http://127.0.0.1:3001",
    # Production Render domains
    "https://iubat-smartlibrary-backend.onrender.com",   # Your backend URL
    "https://iubat-smartlibrary-frontend.onrender.com",  # Your frontend URL
]
